#编译的base路径
CC = g++
CPPFLAG = -Wall -Werror -g -w -fPIC -DWITH_NONAMESPACES -fno-use-cxa-atexit -fexceptions -DWITH_DOM  -DWITH_OPENSSL -DSOAP_DEBUG  

BASE_DIR=.
GSOAP_DIR=/root/gsoap-2.8/gsoap
SOURCE=$(BASE_DIR)
SOURCE_CODE=../../..
#include path
INCLUDE +=-I$(SOURCE)/include -I$(GSOAP_DIR) -I$(GSOAP_DIR)/src  -I$(GSOAP_DIR)/import  -I$(BASE_DIR) 
#link path
LIB= -L../../release/lib -L/nvrs/lib -lssl -lcrypto
#proxy obj
PROXYSOURCE=$(BASE_DIR)/proxycpp


#源代码路径 源代码只编译一次 对代码进行分批编译
SRC= $(SOURCE)/stdsoap2.o  $(SOURCE)/soapC.o $(SOURCE)/soapClient.o $(SOURCE)/main.o $(SOURCE)/wsaapi.o $(SOURCE)/wsseapi.o $(SOURCE)/threads.o $(SOURCE)/duration.o  $(SOURCE)/smdevp.o $(SOURCE)/mecevp.o $(SOURCE)/dom.o $(ProxyOBJ)

ProxyOBJ=$(PROXYSOURCE)/soapDeviceBindingProxy.o $(PROXYSOURCE)/soapMediaBindingProxy.o 

#目标.o文件生成规则
OBJECTS = $(patsubst %.cpp,%.o,$(SRC))


#目标库名
TARGET=testSoap

#CPPFLAG = -Wall  -g   -DWITH_OPENSSL 

all: $(TARGET) 
  
$(TARGET):$(OBJECTS) 
	$(CC) -o $(TARGET) $(CPPFLAG) $(OBJECTS)  $(INCLUDE)  $(LIB)

$(OBJECTS):%.o : %.cpp
	$(CC) -c $(CPPFLAG) $(INCLUDE) $< -o $@
  
clean:
	rm -rf  $(OBJECTS) 

